spring.application.name=neodemanda

server.port=8080

# DevTools: reinicio automatico ao recompilar as classes
spring.devtools.restart.enabled=true

# Configuracao do Banco em Memoria H2
spring.datasource.url=jdbc:h2:mem:neodemandadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Ativa o console web do H2 para visualizar tabelas pelo navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console